%% rebuild_vit_native.m - Rebuild ViT-Tiny as native MATLAB dlnetwork
% This script imports the ONNX model, rebuilds it using only native MATLAB
% layers (no autogenerated layers), transfers all weights, and verifies
% numerical equivalence.
%
% Architecture: ViT-Tiny (DeiT-Tiny)
%   - Input: 224x224x3 images
%   - Patch embedding: Conv2D 16x16 stride 16, 3->192 channels (196 patches)
%   - CLS token prepended -> 197 tokens
%   - Learned positional embedding added
%   - 12 transformer blocks: LN -> 3-head self-attention -> LN -> MLP(192->768->192)
%   - Final LayerNorm -> CLS token extraction -> FC 192->1000
%   - 5.7M parameters

clear; clc;
projectDir = fileparts(mfilename('fullpath'));
cd(projectDir);

%% ========================================================================
%  PHASE 1: Import ONNX model (reference) and extract weights
%  ========================================================================
fprintf('=== Phase 1: Loading ONNX model and extracting weights ===\n');

% Import ONNX model as reference for equivalence testing
onnxNet = importNetworkFromONNX('model.onnx');
fprintf('ONNX model imported (reference): %d layers\n', numel(onnxNet.Layers));

% Load weights extracted from ONNX via Python
W = load('vit_weights.mat');
fprintf('Loaded %d weight tensors from vit_weights.mat\n', numel(fieldnames(W)));

%% ========================================================================
%  PHASE 2: Build native dlnetwork layer graph
%  ========================================================================
fprintf('\n=== Phase 2: Building native dlnetwork ===\n');

embedDim = 192;
numHeads = 3;
mlpDim = 768;
numBlocks = 12;
numPatches = 196;  % 14x14
seqLen = 197;      % 196 patches + 1 CLS token
numClasses = 1000;
patchSize = 16;

% --- Patch Embedding ---
layers = [
    imageInputLayer([224 224 3], Normalization="none", Name="input")
    convolution2dLayer(patchSize, embedDim, Stride=patchSize, ...
        Padding=0, Name="patch_conv")
    PatchFlattenLayer(embedDim, "patch_flatten")
    embeddingConcatenationLayer(Name="cls_prepend")
    AddPositionEmbeddingLayer(embedDim, seqLen, "pos_embed")
];
lgraph = layerGraph(layers);

% --- Transformer Blocks ---
prevLayerName = "pos_embed";

for b = 0:(numBlocks-1)
    prefix = sprintf("block%d_", b);

    % LayerNorm 1
    ln1 = layerNormalizationLayer(Name=prefix+"ln1");
    lgraph = addLayers(lgraph, ln1);
    lgraph = connectLayers(lgraph, prevLayerName, prefix+"ln1");

    % Self-Attention
    attn = selfAttentionLayer(numHeads, embedDim, Name=prefix+"attn");
    lgraph = addLayers(lgraph, attn);
    lgraph = connectLayers(lgraph, prefix+"ln1", prefix+"attn");

    % Residual Add 1
    add1 = additionLayer(2, Name=prefix+"add1");
    lgraph = addLayers(lgraph, add1);
    lgraph = connectLayers(lgraph, prefix+"attn", prefix+"add1/in1");
    lgraph = connectLayers(lgraph, prevLayerName, prefix+"add1/in2");

    % LayerNorm 2
    ln2 = layerNormalizationLayer(Name=prefix+"ln2");
    lgraph = addLayers(lgraph, ln2);
    lgraph = connectLayers(lgraph, prefix+"add1", prefix+"ln2");

    % MLP: FC1 -> GELU -> FC2
    fc1 = fullyConnectedLayer(mlpDim, Name=prefix+"fc1");
    act = geluLayer(Name=prefix+"gelu");
    fc2 = fullyConnectedLayer(embedDim, Name=prefix+"fc2");
    lgraph = addLayers(lgraph, [fc1; act; fc2]);
    lgraph = connectLayers(lgraph, prefix+"ln2", prefix+"fc1");

    % Residual Add 2
    add2 = additionLayer(2, Name=prefix+"add2");
    lgraph = addLayers(lgraph, add2);
    lgraph = connectLayers(lgraph, prefix+"fc2", prefix+"add2/in1");
    lgraph = connectLayers(lgraph, prefix+"add1", prefix+"add2/in2");

    prevLayerName = prefix + "add2";
end

% --- Final LayerNorm + CLS extraction + Classification Head ---
finalLayers = [
    layerNormalizationLayer(Name="final_ln")
    indexing1dLayer("first", Name="cls_extract")
    fullyConnectedLayer(numClasses, Name="head")
];
lgraph = addLayers(lgraph, finalLayers);
lgraph = connectLayers(lgraph, prevLayerName, "final_ln");

% Create dlnetwork
nativeNet = dlnetwork(lgraph);
fprintf('Native dlnetwork created: %d layers\n', numel(nativeNet.Layers));

%% ========================================================================
%  PHASE 3: Transfer weights from ONNX to native network
%  ========================================================================
fprintf('\n=== Phase 3: Transferring weights ===\n');

% Helper: set a learnable by layer name and parameter name
    function net = setWeight(net, layerName, paramName, value)
        L = net.Learnables;
        idx = L.Layer == layerName & L.Parameter == paramName;
        if ~any(idx)
            error('Learnable not found: %s / %s', layerName, paramName);
        end
        L.Value{idx} = dlarray(single(value));
        net.Learnables = L;
    end

% --- Patch Embedding Conv2D ---
% PyTorch [O,I,H,W] -> MATLAB [H,W,I,O]
convW = permute(double(W.patch_embed_proj_weight), [3, 4, 2, 1]);
convB = reshape(double(W.patch_embed_proj_bias), [1, 1, embedDim]);
nativeNet = setWeight(nativeNet, "patch_conv", "Weights", convW);
nativeNet = setWeight(nativeNet, "patch_conv", "Bias", convB);
fprintf('  Patch conv weights set\n');

% --- CLS Token ---
clsToken = reshape(double(squeeze(W.cls_token)), [], 1);  % [192,1]
nativeNet = setWeight(nativeNet, "cls_prepend", "Weights", clsToken);
fprintf('  CLS token set\n');

% --- Positional Embedding ---
posEmbed = squeeze(double(W.pos_embed));  % [1,197,192] -> [197,192]
posEmbed = posEmbed';  % -> [192,197]
nativeNet = setWeight(nativeNet, "pos_embed", "Weights", posEmbed);
fprintf('  Position embedding set\n');

% --- MatMul weight index mapping per block ---
qkvIdx  = [1095 1109 1123 1137 1151 1165 1179 1193 1207 1221 1235 1249];
outIdx  = [1106 1120 1134 1148 1162 1176 1190 1204 1218 1232 1246 1260];
fc1Idx  = [1107 1121 1135 1149 1163 1177 1191 1205 1219 1233 1247 1261];
fc2Idx  = [1108 1122 1136 1150 1164 1178 1192 1206 1220 1234 1248 1262];

for b = 0:(numBlocks-1)
    prefix = sprintf("block%d_", b);
    bi = b + 1;  % 1-indexed

    % --- LayerNorm 1 ---
    ln1Scale = reshape(double(W.(sprintf('blocks_%d_norm1_weight', b))), [], 1);
    ln1Offset = reshape(double(W.(sprintf('blocks_%d_norm1_bias', b))), [], 1);
    nativeNet = setWeight(nativeNet, prefix+"ln1", "Scale", ln1Scale);
    nativeNet = setWeight(nativeNet, prefix+"ln1", "Offset", ln1Offset);

    % --- Self-Attention weights ---
    % QKV weights: ONNX [inputDim, 3*embedDim] -> transpose -> [3*embedDim, inputDim]
    qkvW = double(W.(sprintf('onnx__MatMul_%d', qkvIdx(bi))))';  % [576, 192]
    qW = qkvW(1:embedDim, :);
    kW = qkvW(embedDim+1:2*embedDim, :);
    vW = qkvW(2*embedDim+1:end, :);

    % QKV biases: [576] -> split into Q[192], K[192], V[192]
    qkvB = double(W.(sprintf('blocks_%d_attn_qkv_bias', b)));
    qkvB = qkvB(:);
    qB = qkvB(1:embedDim);
    kB = qkvB(embedDim+1:2*embedDim);
    vB = qkvB(2*embedDim+1:end);

    % Output projection
    outW = double(W.(sprintf('onnx__MatMul_%d', outIdx(bi))))';  % [192, 192]
    outB = reshape(double(W.(sprintf('blocks_%d_attn_proj_bias', b))), [], 1);

    nativeNet = setWeight(nativeNet, prefix+"attn", "QueryWeights", qW);
    nativeNet = setWeight(nativeNet, prefix+"attn", "KeyWeights", kW);
    nativeNet = setWeight(nativeNet, prefix+"attn", "ValueWeights", vW);
    nativeNet = setWeight(nativeNet, prefix+"attn", "OutputWeights", outW);
    nativeNet = setWeight(nativeNet, prefix+"attn", "QueryBias", qB);
    nativeNet = setWeight(nativeNet, prefix+"attn", "KeyBias", kB);
    nativeNet = setWeight(nativeNet, prefix+"attn", "ValueBias", vB);
    nativeNet = setWeight(nativeNet, prefix+"attn", "OutputBias", outB);

    % --- LayerNorm 2 ---
    ln2Scale = reshape(double(W.(sprintf('blocks_%d_norm2_weight', b))), [], 1);
    ln2Offset = reshape(double(W.(sprintf('blocks_%d_norm2_bias', b))), [], 1);
    nativeNet = setWeight(nativeNet, prefix+"ln2", "Scale", ln2Scale);
    nativeNet = setWeight(nativeNet, prefix+"ln2", "Offset", ln2Offset);

    % --- MLP FC1 ---
    fc1W = double(W.(sprintf('onnx__MatMul_%d', fc1Idx(bi))))';  % [768, 192]
    fc1B = reshape(double(W.(sprintf('blocks_%d_mlp_fc1_bias', b))), [], 1);
    nativeNet = setWeight(nativeNet, prefix+"fc1", "Weights", fc1W);
    nativeNet = setWeight(nativeNet, prefix+"fc1", "Bias", fc1B);

    % --- MLP FC2 ---
    fc2W = double(W.(sprintf('onnx__MatMul_%d', fc2Idx(bi))))';  % [192, 768]
    fc2B = reshape(double(W.(sprintf('blocks_%d_mlp_fc2_bias', b))), [], 1);
    nativeNet = setWeight(nativeNet, prefix+"fc2", "Weights", fc2W);
    nativeNet = setWeight(nativeNet, prefix+"fc2", "Bias", fc2B);

    fprintf('  Block %d weights set\n', b);
end

% --- Final LayerNorm ---
nativeNet = setWeight(nativeNet, "final_ln", "Scale", ...
    reshape(double(W.norm_weight), [], 1));
nativeNet = setWeight(nativeNet, "final_ln", "Offset", ...
    reshape(double(W.norm_bias), [], 1));
fprintf('  Final LayerNorm weights set\n');

% --- Classification Head ---
headW = double(W.head_weight);  % [1000, 192] already [output, input]
headB = reshape(double(W.head_bias), [], 1);
nativeNet = setWeight(nativeNet, "head", "Weights", headW);
nativeNet = setWeight(nativeNet, "head", "Bias", headB);
fprintf('  Classification head weights set\n');

%% ========================================================================
%  PHASE 4: Verify numerical equivalence
%  ========================================================================
fprintf('\n=== Phase 4: Verifying numerical equivalence ===\n');

numTests = 5;
maxErrors = zeros(numTests, 1);
rng(42);

for t = 1:numTests
    % Generate random test image
    testImg = dlarray(single(randn(224, 224, 3, 1)), "SSCB");

    % Run ONNX reference model
    onnxOut = predict(onnxNet, testImg);
    onnxOut = double(extractdata(onnxOut));
    onnxOut = onnxOut(:);

    % Run native model
    nativeOut = predict(nativeNet, testImg);
    nativeOut = double(extractdata(nativeOut));
    nativeOut = nativeOut(:);

    % Compare (ensure both are column vectors of same length)
    assert(numel(onnxOut) == numel(nativeOut), ...
        'Output size mismatch: ONNX=%d Native=%d', numel(onnxOut), numel(nativeOut));
    maxErrors(t) = max(abs(onnxOut - nativeOut));
    fprintf('  Test %d: max abs error = %.2e\n', t, maxErrors(t));
end

overallMaxError = max(maxErrors);
fprintf('\n  Overall max absolute error: %.2e\n', overallMaxError);
if overallMaxError < 1e-3
    fprintf('  PASS: Native network is numerically equivalent (< 1e-3 tolerance).\n');
else
    fprintf('  WARNING: Error exceeds 1e-3 threshold. Investigate weight mapping.\n');
end

%% ========================================================================
%  PHASE 5: Save native network and report
%  ========================================================================
fprintf('\n=== Phase 5: Saving native network ===\n');
save('vit_native_net.mat', 'nativeNet', '-v7.3');
fprintf('Native network saved to vit_native_net.mat\n');

% Print network summary
summary(nativeNet);

fprintf('\n=== Native ViT-Tiny rebuild complete ===\n');
fprintf('Total layers: %d\n', numel(nativeNet.Layers));
fprintf('Total learnables: %d\n', height(nativeNet.Learnables));

%% ========================================================================
%  Helper functions
%  ========================================================================
